#python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/15th/hpa-cam-infer.csv ??
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/41st/ensemble-cell-transformer-3.csv
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/42nd/HPA_2021_InferenceandSubmission_LB047.csv
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/43rd/HPA_baseline_cell_segmentation_21027896.csv
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/44th/Fork_of_Fork_of_last_sub_0_21018678.csv
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/45th/hpa-preptrained-ensemble-infer-v6.csv
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/46th/HPA_faster_final_ensemble_wo_rot_exp2.csv
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/47th/mask_inference_21024146.csv
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/48th/HPA_INFERENCE_clean_Public_Private_single.csv
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/49th/HPS_Make_Final_Sub_exp42.csv
python segmentation_matching.py -file=/data/kaggle-dataset/mAPscoring/50th/512image_big_student_1_1_cell_res_11_128.csv
