# nova-networks/HPA-nova
dpp:
  mode: 'train'
  
basic:
  seed: 233
  GPU: 1
  debug: True
  id: 'unnamed'
  mode: train
  search: False
  amp: 'Native'

experiment:
  name: 'RandomKTrainTestSplit'
  random_state: 233
  fold: 1
  run_fold: -1
  batch_sampler: False
  weight: True
  method: 'sqrt'
  preprocess: JPEG_512_pan
  image_only: True
  skip_outlier: True
  outlier: train
  count: 10 # same as num_cells
  valid_count: 1042
  num_cells: 10
  n_channels: 4
  num_train: 6268 # Total number of training images
  img_weight: 0
  file: 'bbbc2_train.csv' # training csv, put in /dataloaders/split/
  csv_valid: 'bbbc2_valid.csv' # validation csv, put in /dataloaders/split/
  csv_test: 'bbbc2_test.csv' # test csv, put in /dataloaders/split/ --> change in init
  smoothing: 0

data:
  dir: 'preprocessing/train_bbbc_2/cell'
  # dir: '../kaggle_HPA/2021/data/kaggle-dataset/CAM_images/images/cellpose_segmented/6_train_240220_RGB/cropped_cells'

model:
  name: 'resnet50' # 'resnet50' # OG: 'tf_efficientnet_b3', 4 channel 'efficientnet2'
  from_checkpoint: 'none'
  out_feature: 693
  params:
    dropout: 0.5
    pretrained: True

train:
  dir: './results'
  batch_size: 1
  num_epochs: 300
  validate_every: 1
  gradcam_every: 50
  cutmix: False
  beta: 1
  cutmix_prob: 1
  cutmix_prob_increase: 0
  validations_round: 1
  freeze_backbond: 1
  freeze_top_layer_groups: 0
  freeze_start_epoch: 0

eval:
  batch_size: 1

loss:
# og: bce
  name: 'weighted_ce_loss' 
  cellweight: 0.1
  class_weight: [ 0.02531037, 0.06579517, 0.04364358, 0.04229549, 0.03539962,
       0.03934447, 0.04536092, 0.03703704, 0.04307305, 0.05735393,
       0.04914732, 0.30151134, 0.0418487 , 0.0347524 , 0.03067138,
       0.10425721, 0.03305898, 0.05933908, 0.15075567]
  params:
   weight: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
   eps: 0.1
    # reduction: 'none'

optimizer:
  name: 'Adam'
  step: 1
  params:
    lr: 0.0002
    weight_decay: 0

scheduler:
  name: 'CosineAnnealingLR'
  warm_up: True
  params:
    factor: 0.99 # OG 0.1
    patience: 50

transform:
  name: 's_0220/sin_256_final' # in configs/augmentation
  val_name: 's_0220/sin_256_final'
  test_name: 's_0220/test'
  num_preprocessor: 6
  size: 128
